# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  primary:
    ssl_mode: :disabled
    sslverify: false
    adapter: mysql2
    charset: utf8mb4
    collation: utf8mb4_bin
    encoding: utf8mb4
    pool: 30
    username: <%= Rails.application.credentials.dig(:database, :primary, :username) %>
    password: <%= Rails.application.credentials.dig(:database, :primary, :password) %>
    host: <%= Rails.application.credentials.dig(:database, :primary, :host) %>
    port: <%= Rails.application.credentials.dig(:database, :primary, :port) %>
    database: <%= Rails.application.credentials.dig(:database, :primary, :database) %>
    timeout: 10000

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
